# fallback_helsinki.py
import pandas as pd

def get_fallback_tickers() -> pd.DataFrame:
    rows = [
        # ---- ISOT ----
        {"symbol":"NDA-FI.HE","name":"Nordea Bank Abp","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Isot"},
        {"symbol":"KNEBV.HE","name":"KONE B","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Isot"},
        {"symbol":"NOKIA.HE","name":"Nokia","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Isot"},
        {"symbol":"SAMPO.HE","name":"Sampo","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Isot"},
        {"symbol":"FORTUM.HE","name":"Fortum","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Isot"},
        {"symbol":"NESTE.HE","name":"Neste","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Isot"},
        {"symbol":"UPM.HE","name":"UPM-Kymmene","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Isot"},
        {"symbol":"METSO.HE","name":"Metso","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Isot"},
        {"symbol":"ELISA.HE","name":"Elisa","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Isot"},
        {"symbol":"WRT1V.HE","name":"Wärtsilä","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Isot"},
        {"symbol":"KESKOB.HE","name":"Kesko B","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Isot"},
        {"symbol":"ORNBV.HE","name":"Orion B","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Isot"},
        {"symbol":"STERV.HE","name":"Stora Enso R","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Isot"},
        {"symbol":"STEAV.HE","name":"Stora Enso A","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Isot"},

        # ---- KESKISUURET ----
        {"symbol":"KCR.HE","name":"Konecranes","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Keskisuuret"},
        {"symbol":"VALMT.HE","name":"Valmet","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Keskisuuret"},
        {"symbol":"HUH1V.HE","name":"Huhtamäki","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Keskisuuret"},
        {"symbol":"KEMIRA.HE","name":"Kemira","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Keskisuuret"},
        {"symbol":"KOJAMO.HE","name":"Kojamo","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Keskisuuret"},
        {"symbol":"KALMAR.HE","name":"Kalmar","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Keskisuuret"},
        {"symbol":"TIETO.HE","name":"Tietoevry","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Keskisuuret"},
        {"symbol":"OUT1V.HE","name":"Outokumpu","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Keskisuuret"},
        {"symbol":"SANOMA.HE","name":"Sanoma","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Keskisuuret"},
        {"symbol":"VAIAS.HE","name":"Vaisala","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Keskisuuret"},
        {"symbol":"TTALO.HE","name":"Terveystalo","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Keskisuuret"},
        {"symbol":"TYRES.HE","name":"Nokian Renkaat","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Keskisuuret"},

        # ---- PIENET ----
        {"symbol":"ALMA.HE","name":"Alma Media","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"PUUILO.HE","name":"Puuilo","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"FSKRS.HE","name":"Fiskars","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"METSB.HE","name":"Metsä Board B","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"QTCOM.HE","name":"Qt Group","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"KEMPOWR.HE","name":"Kempower","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"PON1V.HE","name":"Ponsse","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"AKTIA.HE","name":"Aktia","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"ALBBV.HE","name":"Ålandsbanken B","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"HARVIA.HE","name":"Harvia","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"SCANFL.HE","name":"Scanfil","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"OLVAS.HE","name":"Olvi A","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"YIT.HE","name":"YIT","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"REG1V.HE","name":"Revenio Group","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"MUSTI.HE","name":"Musti Group","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"CTY1S.HE","name":"Citycon","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"FIA1S.HE","name":"Finnair","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"EVLI.HE","name":"Evli","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"TOKMAN.HE","name":"Tokmanni","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"MEKKO.HE","name":"Marimekko","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"BITTI.HE","name":"Bittium","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"EQV1V.HE","name":"eQ","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"LINDEX.HE","name":"Lindex Group","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"TALLINK.HE","name":"AS Tallink Grupp","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"RAIKV.HE","name":"Raisio K","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"RAIVV.HE","name":"Raisio V","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"ATRAV.HE","name":"Atria A","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"LAT1V.HE","name":"Lassila & Tikanoja","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"OMASP.HE","name":"Oma Säästöpankki","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"PIHLIS.HE","name":"Pihlajalinna","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"VIK1V.HE","name":"Viking Line","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"ENENTO.HE","name":"Enento Group","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"PAMPALO.HE","name":"Endomines Finland","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"CAPMAN.HE","name":"CapMan","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"WITH.HE","name":"WithSecure","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"RELAIS.HE","name":"Relais Group","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"FSECURE.HE","name":"F-Secure","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"ICP1V.HE","name":"Incap","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},
        {"symbol":"ETTE.HE","name":"Etteplan","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"Pienet"},

        # ---- FIRST NORTH ----
        {"symbol":"ADMCM.HE","name":"Admicom","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"First North"},
        {"symbol":"FARON.HE","name":"Faron Pharmaceuticals","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"First North"},
        {"symbol":"NEXSTM.HE","name":"Nexstim","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"First North"},
        {"symbol":"EAGLE.HE","name":"Eagle Filters Group","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"First North"},
        {"symbol":"HERANTIS.HE","name":"Herantis Pharma","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"First North"},
        {"symbol":"QPR1V.HE","name":"QPR Software","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"First North"},
        {"symbol":"SUMMA.HE","name":"Summa Defence","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"First North"},
        {"symbol":"CANATU.HE","name":"Canatu","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"First North"},
        {"symbol":"HEALTH.HE","name":"Nightingale Health","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"First North"},
        {"symbol":"SFOODS.HE","name":"Solar Foods","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"First North"},
        {"symbol":"PIIPPO.HE","name":"Piippo","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"First North"},
        {"symbol":"PALLAS.HE","name":"Pallas Air","exchange":"Nasdaq Helsinki","country":"FI","asset_class":"Equity","currency":"EUR","segment":"First North"},
    ]
    return pd.DataFrame(rows)
